name: unit tests

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: install dependencies
      run: 
#        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit tests
      run: python -m unittest sensor_api/tests/test_visit_sensor.py
      # unittest sensor_api.tests.test_visit_sensor
      # python -m unittest discover -s '/sensor_api/tests' -p 'test_visit*.py' 
      # #unittest sensor_api/tests/test_visit_sensor.py #removed the -m